(define (problem p)
   (:domain rc)
   (:init
      (ppointing_satellite0_Phenomenon6_)
      (ppower_on_instrument0_)
      (tdrmtake_image_satellite0_Phenomenon4_instrument0_thermograph0_)
      (tdrmturn_to_satellite0_Phenomenon4_Phenomenon6_)
      (tdrmturn_to_satellite0_Phenomenon4_GroundStation2_)
      (tdrmcalibrate_satellite0_instrument0_GroundStation2_)
      (tdrmturn_to_satellite0_GroundStation2_Phenomenon6_)
      (tdrmturn_to_satellite0_GroundStation2_Phenomenon4_)
      (tdrmswitch_on_instrument0_satellite0_)
   )
   (:goal (and
      (burmauto_calibrate_satellite0_instrument0_)
   ))
)
